# اسم التطبيق
spring.application.name=movies-backend
server.port=8081

# 1. عنوان الداتا بيس (الموجودة في جهازك)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

# 2. اسم المستخدم (الافتراضي)
spring.datasource.username=postgres

# 3. الباسورد (الذي كتبتيه عند تثبيت البرنامج)
spring.datasource.password=1234

# 4. التحديث التلقائي
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect